version: 3

dotenv: ['.env']

tasks:
  whoami:
    cmds:
      - echo "Snapdragon 845 VoLTE"
  download-google-pixel-3-firmware:
    cmds:
      - wget -P "Firmwares/Google/Pixel 3" https://dl.google.com/dl/android/aosp/blueline-sp1a.210812.016.c2-factory-fa981d87.zip
